import { listModelCaseSlugs } from "@/lib/model-cases";
import { getSiteUrl } from "@/lib/site";
import type { CatalogPage } from "@/lib/marketing-agent/types";

const STATIC_PAGES: CatalogPage[] = [
  {
    path: "",
    language: "ja",
    pageType: "home",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "JA home",
  },
  {
    path: "/cases",
    language: "ja",
    pageType: "listing",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "JA product listing",
  },
  {
    path: "/for-makers",
    language: "ja",
    pageType: "guide",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "For product providers",
  },
  {
    path: "/for-partners",
    language: "ja",
    pageType: "guide",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "For sales partners",
  },
  {
    path: "/pricing",
    language: "ja",
    pageType: "pricing",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "JA pricing",
  },
  {
    path: "/how-to-sell-in-japan",
    language: "ja",
    pageType: "guide",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "How to sell in Japan (JA)",
  },
  {
    path: "/product-showcase",
    language: "ja",
    pageType: "showcase",
    seoImportance: "medium",
    published: true,
    fetchLive: true,
    label: "Product showcase JA",
  },
  {
    path: "/register/maker",
    language: "ja",
    pageType: "register",
    seoImportance: "medium",
    published: true,
    fetchLive: true,
    label: "Maker register JA",
  },
  {
    path: "/register/partner",
    language: "ja",
    pageType: "register",
    seoImportance: "medium",
    published: true,
    fetchLive: true,
    label: "Partner register JA",
  },
  {
    path: "/contact",
    language: "ja",
    pageType: "contact",
    seoImportance: "low",
    published: true,
    fetchLive: false,
    label: "Contact JA",
  },
  {
    path: "/company",
    language: "ja",
    pageType: "company",
    seoImportance: "low",
    published: true,
    fetchLive: true,
    label: "Company",
  },
  {
    path: "/terms",
    language: "ja",
    pageType: "legal",
    seoImportance: "low",
    published: true,
    fetchLive: false,
    label: "Terms",
  },
  {
    path: "/privacy",
    language: "ja",
    pageType: "legal",
    seoImportance: "low",
    published: true,
    fetchLive: false,
    label: "Privacy",
  },
  {
    path: "/en",
    language: "en",
    pageType: "home",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "EN home",
  },
  {
    path: "/en/cases",
    language: "en",
    pageType: "listing",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "EN opportunities",
  },
  {
    path: "/en/japan-market-entry",
    language: "en",
    pageType: "guide",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "Japan market entry hub",
  },
  {
    path: "/en/japan-market-entry/how-to-enter-the-japanese-market",
    language: "en",
    pageType: "guide",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "How to enter the Japanese market",
  },
  {
    path: "/en/japan-market-entry/how-to-find-japanese-distributors",
    language: "en",
    pageType: "guide",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "Find Japanese distributors",
  },
  {
    path: "/en/japan-market-entry/how-to-find-a-japanese-distributor",
    language: "en",
    pageType: "guide",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "Find a Japanese distributor",
  },
  {
    path: "/en/japan-market-entry/how-to-find-japanese-retailers",
    language: "en",
    pageType: "guide",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "Find Japanese retailers",
  },
  {
    path: "/en/how-to-sell-in-japan",
    language: "en",
    pageType: "guide",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "How to sell in Japan (EN)",
  },
  {
    path: "/en/japan-market-for-functional-food-brands",
    language: "en",
    pageType: "guide",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "Japan market for functional food",
  },
  {
    path: "/en/japan-partner-demand-snapshot",
    language: "en",
    pageType: "guide",
    seoImportance: "medium",
    published: true,
    fetchLive: true,
    label: "Japan partner demand snapshot",
  },
  {
    path: "/en/product-showcase",
    language: "en",
    pageType: "showcase",
    seoImportance: "medium",
    published: true,
    fetchLive: true,
    label: "Featured brands",
  },
  {
    path: "/en/register/maker",
    language: "en",
    pageType: "register",
    seoImportance: "high",
    published: true,
    fetchLive: true,
    label: "List your brand",
  },
  {
    path: "/en/register/partner",
    language: "en",
    pageType: "register",
    seoImportance: "medium",
    published: true,
    fetchLive: true,
    label: "Partner registration EN",
  },
  {
    path: "/en/contact",
    language: "en",
    pageType: "contact",
    seoImportance: "low",
    published: true,
    fetchLive: false,
    label: "Contact EN",
  },
  {
    path: "/en/pricing",
    language: "en",
    pageType: "pricing",
    seoImportance: "medium",
    published: true,
    fetchLive: true,
    label: "EN pricing",
  },
];

export function listPublicCatalogPages(): CatalogPage[] {
  const modelPages: CatalogPage[] = listModelCaseSlugs().map((slug) => ({
    path: `/en/model-cases/${slug}`,
    language: "en" as const,
    pageType: "model_case" as const,
    seoImportance: "medium" as const,
    published: true,
    fetchLive: true,
    label: `Model case ${slug}`,
  }));

  return [...STATIC_PAGES, ...modelPages];
}

export function catalogPathToUrl(path: string, origin = getSiteUrl()): string {
  if (!path) return origin;
  return `${origin}${path}`;
}

export function listFetchTargets(): CatalogPage[] {
  return listPublicCatalogPages().filter(
    (page) => page.fetchLive && page.published && page.seoImportance !== "low",
  );
}
